apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin-node
  labels:
    app: litecoin-node
spec:
  serviceName: litecoin-node
  replicas: 1
  selector:
    matchLabels:
      app: litecoin-node
  template:
    metadata:
      labels:
        app: litecoin-node
    spec:
      containers:
      - name: litecoin-node
        image: dmg8/litecoin:1.22
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        volumeMounts:
        - name: litecoin-data
          mountPath: /var/litecoin
  volumeClaimTemplates:
  - metadata:
      name: litecoin-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
---
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: fast
#provisioner: k8s.io/minikube-hostpath
#parameters:
#  type: pd-ssd
