apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin-node
  labels:
    app: litecoin-node
spec:
  serviceName: litecoin-node
  replicas: 1
  selector:
    matchLabels:
      app: litecoin-node
  template:
    metadata:
      labels:
        app: litecoin-node
    spec:
      containers:
      - name: litecoin-node
        image: dmg8/litecoin:latest
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "300m"
            memory: 750m
        volumeMounts:
        - name: litecoin-data
          mountPath: /var/litecoin
  volumeClaimTemplates:
  - metadata:
      name: litecoin-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
